<?php

namespace Database\Seeders;

use App\Enums\SealStatus;
use App\Enums\TripStatus;
use App\Enums\TripTransportationMode;
use App\Enums\TripType;
use App\Models\Customer;
use App\Models\CustomerLocation;
use App\Models\Seal;
use App\Models\Trip;
use App\Models\TripDocument;
use App\Models\TripEvent;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TripSeeder extends Seeder
{
    public function run(): void
    {
        $total = 0;

        foreach ($this->scenariosByCustomer() as $email => $scenarios) {
            $customer = Customer::where('email', $email)->first();
            if (!$customer) continue;

            $user = User::where('customer_id', $customer->id)->firstOrFail();

            foreach ($scenarios as $def) {
                if (Trip::where('trip_ref', $def['trip_ref'])->exists()) {
                    $total++;
                    continue;
                }

                $needsSeal = $def['needs_seal'] ?? false;
                $sealStatus = $def['seal_final_status'] ?? SealStatus::Assigned;
                unset($def['needs_seal'], $def['seal_final_status']);

                // Assign an available seal if this trip needs one
                $seal = null;
                if ($needsSeal) {
                    $seal = Seal::where('customer_id', $customer->id)
                        ->where('status', SealStatus::InInventory->value)
                        ->whereNull('trip_id')
                        ->first();
                }

                $trip = Trip::create(array_merge($def, [
                    'customer_id' => $customer->id,
                    'created_by_id' => $user->id,
                    'seal_id' => $seal?->id,
                    'tracking_token' => Str::random(32),
                ]));

                if ($seal) {
                    $seal->update([
                        'status' => $sealStatus->value,
                        'trip_id' => $trip->id,
                    ]);
                }

                $this->seedEvents($trip, $user);
                $this->seedDocuments($trip, $user);

                $total++;
            }
        }

        $this->command->info("  TripSeeder: {$total} trips seeded.");
    }

    // ── Scenario definitions per customer ─────────────────────────────────────

    private function scenariosByCustomer(): array
    {
        return [
            'kiran.verma@vermalogistics.test' => $this->vermaTrips(),
            'meena.iyer@iyerimpex.test' => $this->iyerTrips(),
        ];
    }

    // ── VERMA LOGISTICS (Delhi-based) ─────────────────────────────────────────

    private function vermaTrips(): array
    {
        return [

            // ─────────────────────────────────────────────────────────────────
            // VL-T01 | COMPLETED EXPORT MULTIMODAL
            // Delhi (Mayapuri) → truck → JNPT → vessel → Jebel Ali, UAE
            // Full journey: road leg + sea leg + delivery at Jebel Ali
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T01',
                'status' => TripStatus::Completed,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Multimodal,
                // Driver / Vehicle
                'driver_name' => 'Rajesh Singh',
                'driver_phone' => '9871122334',
                'driver_license' => 'DL0120190054321',
                'driver_aadhaar' => '987612345678',
                'vehicle_number' => 'DL01CA3412',
                'vehicle_type' => 'container_carrier',
                'is_driver_license_verified' => true,
                'is_driver_aadhaar_verified' => true,
                'is_rc_verified' => true,
                'is_verification_done' => true,
                // Cargo
                'container_number' => 'MSCU7401234',
                'container_type' => '40HC',
                'carrier_scac' => 'MSCU',
                'cargo_type' => 'Auto Components',
                'cargo_description' => 'CNC machined engine components, aluminium castings and brake assemblies packed on pallets',
                'hs_code' => '8708.30',
                'gross_weight' => 18500.00,
                'net_weight' => 17800.00,
                'weight_unit' => 'kg',
                'quantity' => 320,
                'quantity_unit' => 'pieces',
                'declared_cargo_value' => 1250000.00,
                'invoice_number' => 'VL-EXP-2024-0412',
                'invoice_date' => now()->subDays(47)->toDateString(),
                'eway_bill_number' => '2312456789123456',
                'eway_bill_validity_date' => now()->subDays(30)->toDateString(),
                // Dispatch
                'dispatch_location_name' => 'Verma Logistics — Mayapuri HO',
                'dispatch_address' => 'Plot 14, Phase II, Mayapuri Industrial Area',
                'dispatch_city' => 'New Delhi',
                'dispatch_state' => 'Delhi',
                'dispatch_pincode' => '110064',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Kiran Verma',
                'dispatch_contact_number' => '9876543205',
                'dispatch_contact_email' => 'dispatch@vermalogistics.test',
                'dispatch_lat' => 28.6358,
                'dispatch_lng' => 77.1022,
                'dispatch_date' => now()->subDays(45)->toDateString(),
                // Delivery
                'delivery_location_name' => 'Al Quoz Industrial Area Warehouse',
                'delivery_address' => 'Warehouse 12, Al Quoz Industrial Area 4',
                'delivery_city' => 'Dubai',
                'delivery_state' => 'Dubai Emirate',
                'delivery_pincode' => '392803',
                'delivery_country' => 'UAE',
                'delivery_contact_person' => 'Ahmed Al Farsi',
                'delivery_contact_number' => '+971501234567',
                'delivery_contact_email' => 'receiving@alquozwh.ae',
                'delivery_lat' => 25.1472,
                'delivery_lng' => 55.2180,
                // Ports
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Jebel Ali Port',
                'destination_port_code' => 'AEJEA',
                'destination_port_category' => 'port',
                // Vessel
                'vessel_name' => 'MSC MAGNIFICA',
                'vessel_imo_number' => 'IMO9387073',
                'voyage_number' => 'IE421A',
                'bill_of_lading' => 'MSCUMN1234567',
                'eta' => now()->subDays(26),
                'etd' => now()->subDays(38),
                // Timeline
                'trip_start_time' => now()->subDays(45),
                'expected_delivery_date' => now()->subDays(22)->toDateString(),
                'actual_delivery_date' => now()->subDays(22)->toDateString(),
                'trip_end_time' => now()->subDays(22),
                // ePOD
                'epod_status' => 'completed',
                'epod_confirmed_at' => now()->subDays(21),
                'epod_confirmation_notes' => 'All 320 pieces received in good condition. Boxes intact, no damage observed.',
                // Meta
                'needs_seal' => true,
                'seal_final_status' => SealStatus::Used,
                'risk_score' => 12.50,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T02 | COMPLETED IMPORT MULTIMODAL
            // Jebel Ali (UAE) → vessel → JNPT → truck → Delhi (Noida)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T02',
                'status' => TripStatus::Completed,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Multimodal,
                'driver_name' => 'Manoj Yadav',
                'driver_phone' => '9899001122',
                'driver_license' => 'UP0220200098765',
                'vehicle_number' => 'UP14BT8821',
                'vehicle_type' => 'container_carrier',
                'is_driver_license_verified' => true,
                'is_verification_done' => true,
                'container_number' => 'MSCU8812345',
                'container_type' => '40GP',
                'carrier_scac' => 'MSCU',
                'cargo_type' => 'Electronic Components',
                'cargo_description' => 'PCBs, semiconductors and display panels — FRAGILE',
                'hs_code' => '8542.31',
                'gross_weight' => 6200.00,
                'net_weight' => 5900.00,
                'weight_unit' => 'kg',
                'quantity' => 48,
                'quantity_unit' => 'cartons',
                'declared_cargo_value' => 3200000.00,
                'invoice_number' => 'VL-IMP-2024-0388',
                'invoice_date' => now()->subDays(52)->toDateString(),
                'eway_bill_number' => '2312789456123000',
                'eway_bill_validity_date' => now()->subDays(12)->toDateString(),
                // Dispatch (origin — Jebel Ali)
                'dispatch_location_name' => 'Jebel Ali Free Zone (JAFZA North)',
                'dispatch_address' => 'JAFZA North, Jebel Ali',
                'dispatch_city' => 'Dubai',
                'dispatch_state' => 'Dubai Emirate',
                'dispatch_pincode' => '17000',
                'dispatch_country' => 'UAE',
                'dispatch_contact_person' => 'Supplier Warehouse',
                'dispatch_contact_number' => '+97148801234',
                'dispatch_contact_email' => 'logistics@jafzasupplier.ae',
                'dispatch_lat' => 24.9857,
                'dispatch_lng' => 55.0272,
                'dispatch_date' => now()->subDays(50)->toDateString(),
                // Delivery (destination — Noida)
                'delivery_location_name' => 'Verma Logistics — NSEZ Noida Warehouse',
                'delivery_address' => 'Unit B-12, Noida Special Economic Zone',
                'delivery_city' => 'Noida',
                'delivery_state' => 'Uttar Pradesh',
                'delivery_pincode' => '201305',
                'delivery_country' => 'India',
                'delivery_contact_person' => 'Kiran Verma',
                'delivery_contact_number' => '9876543205',
                'delivery_contact_email' => 'receiving@vermalogistics.test',
                'delivery_lat' => 28.5706,
                'delivery_lng' => 77.3522,
                // Ports
                'origin_port_name' => 'Jebel Ali Port',
                'origin_port_code' => 'AEJEA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'destination_port_code' => 'INNSA',
                'destination_port_category' => 'port',
                // Vessel
                'vessel_name' => 'MSC GÜLSÜN',
                'vessel_imo_number' => 'IMO9811000',
                'voyage_number' => 'AE421W',
                'bill_of_lading' => 'MSCUMUM7654321',
                'eta' => now()->subDays(33),
                'etd' => now()->subDays(48),
                // Timeline
                'trip_start_time' => now()->subDays(50),
                'expected_delivery_date' => now()->subDays(26)->toDateString(),
                'actual_delivery_date' => now()->subDays(25)->toDateString(),
                'trip_end_time' => now()->subDays(25),
                'epod_status' => 'completed',
                'epod_confirmed_at' => now()->subDays(24),
                'epod_confirmation_notes' => 'All cartons received. 2 cartons had minor dents but contents intact.',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::Used,
                'risk_score' => 18.00,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T03 | ACTIVE — IN_TRANSIT (road leg: Delhi → JNPT)
            // Truck currently on NH-48 heading to JNPT
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T03',
                'status' => TripStatus::InTransit,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Multimodal,
                'driver_name' => 'Suresh Patel',
                'driver_phone' => '9811234567',
                'driver_license' => 'GJ0620200078901',
                'vehicle_number' => 'GJ17AK5566',
                'vehicle_type' => 'container_carrier',
                'is_verification_done' => true,
                'container_number' => 'HLCU4512890',
                'container_type' => '20GP',
                'carrier_scac' => 'HLCU',
                'cargo_type' => 'Pharmaceutical Bulk Drugs',
                'cargo_description' => 'API formulations packed in HDPE drums, temperature-controlled',
                'hs_code' => '3004.90',
                'gross_weight' => 9800.00,
                'net_weight' => 9200.00,
                'weight_unit' => 'kg',
                'quantity' => 80,
                'quantity_unit' => 'drums',
                'declared_cargo_value' => 4500000.00,
                'invoice_number' => 'VL-EXP-2024-0598',
                'invoice_date' => now()->subDays(4)->toDateString(),
                'eway_bill_number' => '2312900123456789',
                'eway_bill_validity_date' => now()->addDays(10)->toDateString(),
                'dispatch_location_name' => 'Verma Logistics — Mayapuri HO',
                'dispatch_address' => 'Plot 14, Phase II, Mayapuri Industrial Area',
                'dispatch_city' => 'New Delhi',
                'dispatch_state' => 'Delhi',
                'dispatch_pincode' => '110064',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Kiran Verma',
                'dispatch_contact_number' => '9876543205',
                'dispatch_contact_email' => 'dispatch@vermalogistics.test',
                'dispatch_lat' => 28.6358,
                'dispatch_lng' => 77.1022,
                'dispatch_date' => now()->subDays(3)->toDateString(),
                'delivery_location_name' => 'Jebel Ali Port',
                'delivery_address' => 'JAFZA, Jebel Ali',
                'delivery_city' => 'Dubai',
                'delivery_country' => 'UAE',
                'delivery_lat' => 24.9857,
                'delivery_lng' => 55.0272,
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Jebel Ali Port',
                'destination_port_code' => 'AEJEA',
                'destination_port_category' => 'port',
                'trip_start_time' => now()->subDays(3),
                'expected_delivery_date' => now()->addDays(22)->toDateString(),
                'last_known_lat' => 22.3072,   // Near Vadodara on NH-48
                'last_known_lng' => 73.1812,
                'last_known_source' => 'driver_mobile',
                'last_tracked_at' => now()->subHours(2),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
                'risk_score' => 22.00,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T04 | ACTIVE — AT_PORT (container at JNPT, awaiting loading)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T04',
                'status' => TripStatus::AtPort,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Multimodal,
                'driver_name' => 'Brijesh Kumar',
                'driver_phone' => '9819988776',
                'vehicle_number' => 'MH04CQ2234',
                'vehicle_type' => 'trailer',
                'is_verification_done' => true,
                'container_number' => 'CMAU3389010',
                'container_type' => '40HC',
                'carrier_scac' => 'CMDU',
                'cargo_type' => 'Textiles & Garments',
                'cargo_description' => 'Ready-made garments in polybags, carton packed — 1500 cartons',
                'hs_code' => '6204.62',
                'gross_weight' => 12000.00,
                'net_weight' => 11500.00,
                'weight_unit' => 'kg',
                'quantity' => 1500,
                'quantity_unit' => 'cartons',
                'declared_cargo_value' => 680000.00,
                'invoice_number' => 'VL-EXP-2024-0601',
                'invoice_date' => now()->subDays(10)->toDateString(),
                'eway_bill_number' => '2312567891234001',
                'eway_bill_validity_date' => now()->addDays(5)->toDateString(),
                'dispatch_location_name' => 'Verma Logistics — NSEZ Noida Warehouse',
                'dispatch_address' => 'Unit B-12, Noida Special Economic Zone',
                'dispatch_city' => 'Noida',
                'dispatch_state' => 'Uttar Pradesh',
                'dispatch_pincode' => '201305',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Warehouse Manager',
                'dispatch_contact_number' => '9871100101',
                'dispatch_lat' => 28.5706,
                'dispatch_lng' => 77.3522,
                'dispatch_date' => now()->subDays(8)->toDateString(),
                'delivery_location_name' => 'Rotterdam Port CFS',
                'delivery_city' => 'Rotterdam',
                'delivery_country' => 'Netherlands',
                'delivery_lat' => 51.9244,
                'delivery_lng' => 4.4777,
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Port of Rotterdam',
                'destination_port_code' => 'NLRTM',
                'destination_port_category' => 'port',
                'trip_start_time' => now()->subDays(8),
                'expected_delivery_date' => now()->addDays(35)->toDateString(),
                'last_known_lat' => 18.9488,
                'last_known_lng' => 72.9511,
                'last_known_source' => 'driver_mobile',
                'last_tracked_at' => now()->subHours(6),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T05 | ACTIVE — ON_VESSEL (JNPT → Rotterdam, currently Red Sea)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T05',
                'status' => TripStatus::OnVessel,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Sea,
                'container_number' => 'MSCU9023456',
                'container_type' => '40HC',
                'carrier_scac' => 'MSCU',
                'cargo_type' => 'Machinery',
                'cargo_description' => 'Industrial water pumps and motor assemblies',
                'hs_code' => '8413.70',
                'gross_weight' => 22000.00,
                'net_weight' => 21000.00,
                'weight_unit' => 'kg',
                'quantity' => 40,
                'quantity_unit' => 'skids',
                'declared_cargo_value' => 2100000.00,
                'invoice_number' => 'VL-EXP-2024-0555',
                'invoice_date' => now()->subDays(18)->toDateString(),
                'dispatch_location_name' => 'Jawaharlal Nehru Port (JNPT)',
                'dispatch_address' => 'JNPT, Sheva, Navi Mumbai',
                'dispatch_city' => 'Navi Mumbai',
                'dispatch_state' => 'Maharashtra',
                'dispatch_pincode' => '400707',
                'dispatch_country' => 'India',
                'dispatch_lat' => 18.9488,
                'dispatch_lng' => 72.9511,
                'dispatch_date' => now()->subDays(15)->toDateString(),
                'delivery_location_name' => 'Port of Rotterdam — ECT Delta Terminal',
                'delivery_city' => 'Rotterdam',
                'delivery_country' => 'Netherlands',
                'delivery_lat' => 51.9244,
                'delivery_lng' => 4.4777,
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Port of Rotterdam',
                'destination_port_code' => 'NLRTM',
                'destination_port_category' => 'port',
                'vessel_name' => 'CMA CGM BOUGAINVILLE',
                'vessel_imo_number' => 'IMO9694685',
                'voyage_number' => 'FAL1-234W',
                'bill_of_lading' => 'CMAMUM0034567',
                'eta' => now()->addDays(14),
                'etd' => now()->subDays(13),
                'trip_start_time' => now()->subDays(15),
                'expected_delivery_date' => now()->addDays(18)->toDateString(),
                // Current vessel position: Red Sea (18.0°N, 40.5°E)
                'last_known_lat' => 18.0000,
                'last_known_lng' => 40.5000,
                'last_known_source' => 'vessel_ais',
                'last_tracked_at' => now()->subHours(1),
                'last_vessel_tracked_at' => now()->subHours(1),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T06 | ACTIVE — IN_TRANSSHIPMENT
            // JNPT → Colombo (transshipment) → Singapore
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T06',
                'status' => TripStatus::InTransshipment,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Sea,
                'container_number' => 'COSU6723001',
                'container_type' => '20GP',
                'carrier_scac' => 'COSU',
                'cargo_type' => 'Chemical Raw Materials',
                'cargo_description' => 'Titanium dioxide in 25kg bags — non-hazardous',
                'hs_code' => '2823.00',
                'gross_weight' => 15000.00,
                'net_weight' => 14800.00,
                'weight_unit' => 'kg',
                'quantity' => 600,
                'quantity_unit' => 'bags',
                'declared_cargo_value' => 900000.00,
                'invoice_number' => 'VL-EXP-2024-0522',
                'invoice_date' => now()->subDays(25)->toDateString(),
                'dispatch_location_name' => 'Jawaharlal Nehru Port (JNPT)',
                'dispatch_city' => 'Navi Mumbai',
                'dispatch_state' => 'Maharashtra',
                'dispatch_country' => 'India',
                'dispatch_lat' => 18.9488,
                'dispatch_lng' => 72.9511,
                'dispatch_date' => now()->subDays(22)->toDateString(),
                'delivery_location_name' => 'Port of Singapore (PSA)',
                'delivery_city' => 'Singapore',
                'delivery_country' => 'Singapore',
                'delivery_lat' => 1.2566,
                'delivery_lng' => 103.8198,
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Port of Singapore (PSA)',
                'destination_port_code' => 'SGSIN',
                'destination_port_category' => 'port',
                'vessel_name' => 'CMA CGM ANTOINE DE SAINT EXUPERY',
                'vessel_imo_number' => 'IMO9776171',
                'voyage_number' => 'AE6-567W',
                'bill_of_lading' => 'COSU123456SGP',
                'eta' => now()->addDays(8),
                'etd' => now()->subDays(20),
                'trip_start_time' => now()->subDays(22),
                'expected_delivery_date' => now()->addDays(12)->toDateString(),
                // Currently at Colombo port transshipment
                'last_known_lat' => 6.9271,
                'last_known_lng' => 79.8612,
                'last_known_source' => 'vessel_ais',
                'last_tracked_at' => now()->subHours(3),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T07 | ACTIVE — VESSEL_ARRIVED
            // Jebel Ali → Mundra, vessel arrived 2 days ago, customs in progress
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T07',
                'status' => TripStatus::VesselArrived,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Multimodal,
                'container_number' => 'MSCU4401122',
                'container_type' => '40GP',
                'carrier_scac' => 'MSCU',
                'cargo_type' => 'Precious Metals — Copper',
                'cargo_description' => 'Electrolytic copper cathodes in wooden crates',
                'hs_code' => '7403.11',
                'gross_weight' => 24000.00,
                'net_weight' => 23800.00,
                'weight_unit' => 'kg',
                'quantity' => 24,
                'quantity_unit' => 'crates',
                'declared_cargo_value' => 12000000.00,
                'invoice_number' => 'VL-IMP-2024-0450',
                'invoice_date' => now()->subDays(22)->toDateString(),
                'dispatch_location_name' => 'Jebel Ali Port',
                'dispatch_city' => 'Dubai',
                'dispatch_country' => 'UAE',
                'dispatch_lat' => 24.9857,
                'dispatch_lng' => 55.0272,
                'dispatch_date' => now()->subDays(20)->toDateString(),
                'delivery_location_name' => 'Verma Logistics — Mayapuri HO',
                'delivery_city' => 'New Delhi',
                'delivery_state' => 'Delhi',
                'delivery_country' => 'India',
                'delivery_lat' => 28.6358,
                'delivery_lng' => 77.1022,
                'origin_port_name' => 'Jebel Ali Port',
                'origin_port_code' => 'AEJEA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Mundra Port (APSEZ)',
                'destination_port_code' => 'INMUN',
                'destination_port_category' => 'port',
                'vessel_name' => 'MSC ANNA',
                'vessel_imo_number' => 'IMO9484702',
                'voyage_number' => 'AE8-112E',
                'bill_of_lading' => 'MSCMUN4400112',
                'eta' => now()->subDays(2),
                'etd' => now()->subDays(18),
                'trip_start_time' => now()->subDays(20),
                'expected_delivery_date' => now()->addDays(5)->toDateString(),
                'last_known_lat' => 22.8381,
                'last_known_lng' => 69.7032,
                'last_known_source' => 'vessel_ais',
                'last_tracked_at' => now()->subHours(4),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T08 | ACTIVE — OUT_FOR_DELIVERY
            // From JNPT (road leg) → Noida warehouse
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T08',
                'status' => TripStatus::OutForDelivery,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Road,
                'driver_name' => 'Dinesh Chauhan',
                'driver_phone' => '9812002244',
                'vehicle_number' => 'MH04DN4411',
                'vehicle_type' => 'container_carrier',
                'is_verification_done' => true,
                'container_number' => 'OOLU7892345',
                'container_type' => '40GP',
                'cargo_type' => 'FMCG — Consumer Goods',
                'cargo_description' => 'Personal care products and detergents packed in master cartons',
                'hs_code' => '3401.11',
                'gross_weight' => 8500.00,
                'net_weight' => 8200.00,
                'weight_unit' => 'kg',
                'quantity' => 1200,
                'quantity_unit' => 'cartons',
                'declared_cargo_value' => 420000.00,
                'invoice_number' => 'VL-IMP-2024-0480',
                'invoice_date' => now()->subDays(14)->toDateString(),
                'eway_bill_number' => '2312111222333444',
                'eway_bill_validity_date' => now()->addDays(2)->toDateString(),
                'dispatch_location_name' => 'Jawaharlal Nehru Port (JNPT) — CFS',
                'dispatch_address' => 'JNPT CFS, Sheva, Navi Mumbai',
                'dispatch_city' => 'Navi Mumbai',
                'dispatch_state' => 'Maharashtra',
                'dispatch_pincode' => '400707',
                'dispatch_country' => 'India',
                'dispatch_lat' => 18.9488,
                'dispatch_lng' => 72.9511,
                'dispatch_date' => now()->subDays(4)->toDateString(),
                'delivery_location_name' => 'Verma Logistics — NSEZ Noida Warehouse',
                'delivery_address' => 'Unit B-12, Noida Special Economic Zone',
                'delivery_city' => 'Noida',
                'delivery_state' => 'Uttar Pradesh',
                'delivery_pincode' => '201305',
                'delivery_country' => 'India',
                'delivery_contact_person' => 'Kiran Verma',
                'delivery_contact_number' => '9876543205',
                'delivery_lat' => 28.5706,
                'delivery_lng' => 77.3522,
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'ICD Tughlakabad',
                'destination_port_code' => 'INTDL',
                'destination_port_category' => 'icd',
                'trip_start_time' => now()->subDays(4),
                'expected_delivery_date' => now()->addDays(1)->toDateString(),
                // Currently near Agra on NH-19/NH-44
                'last_known_lat' => 27.1767,
                'last_known_lng' => 78.0081,
                'last_known_source' => 'driver_mobile',
                'last_tracked_at' => now()->subMinutes(45),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T09 | ACTIVE — DELIVERED (awaiting ePOD)
            // Singapore → JNPT sea, then JNPT → Delhi road, goods delivered
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T09',
                'status' => TripStatus::Delivered,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Multimodal,
                'driver_name' => 'Ramchandran Pillai',
                'driver_phone' => '9811099870',
                'vehicle_number' => 'UP16CZ1234',
                'vehicle_type' => 'container_carrier',
                'is_verification_done' => true,
                'container_number' => 'HLCU2234567',
                'container_type' => '20GP',
                'carrier_scac' => 'HLCU',
                'cargo_type' => 'Electrical Equipment',
                'cargo_description' => 'UPS systems and power conditioning units',
                'hs_code' => '8504.40',
                'gross_weight' => 7800.00,
                'net_weight' => 7500.00,
                'weight_unit' => 'kg',
                'quantity' => 35,
                'quantity_unit' => 'units',
                'declared_cargo_value' => 1800000.00,
                'invoice_number' => 'VL-IMP-2024-0502',
                'invoice_date' => now()->subDays(18)->toDateString(),
                'eway_bill_number' => '2312999888777666',
                'eway_bill_validity_date' => now()->subDays(1)->toDateString(),
                'dispatch_location_name' => 'Port of Singapore (PSA)',
                'dispatch_city' => 'Singapore',
                'dispatch_country' => 'Singapore',
                'dispatch_lat' => 1.2566,
                'dispatch_lng' => 103.8198,
                'dispatch_date' => now()->subDays(16)->toDateString(),
                'delivery_location_name' => 'Verma Logistics — Mayapuri HO',
                'delivery_address' => 'Plot 14, Phase II, Mayapuri Industrial Area',
                'delivery_city' => 'New Delhi',
                'delivery_state' => 'Delhi',
                'delivery_pincode' => '110064',
                'delivery_country' => 'India',
                'delivery_contact_person' => 'Kiran Verma',
                'delivery_contact_number' => '9876543205',
                'delivery_lat' => 28.6358,
                'delivery_lng' => 77.1022,
                'origin_port_name' => 'Port of Singapore (PSA)',
                'origin_port_code' => 'SGSIN',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'destination_port_code' => 'INNSA',
                'destination_port_category' => 'port',
                'vessel_name' => 'EVER GIVEN',
                'vessel_imo_number' => 'IMO9811000',
                'voyage_number' => 'AE5-089E',
                'bill_of_lading' => 'HLCUMUM0012345',
                'eta' => now()->subDays(8),
                'etd' => now()->subDays(15),
                'trip_start_time' => now()->subDays(16),
                'expected_delivery_date' => now()->subDays(1)->toDateString(),
                'actual_delivery_date' => now()->subDays(1)->toDateString(),
                'last_known_lat' => 28.6358,
                'last_known_lng' => 77.1022,
                'last_known_source' => 'driver_mobile',
                'last_tracked_at' => now()->subDays(1),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T10 | COMPLETED DOMESTIC ROAD
            // Delhi (Mayapuri) → Mumbai (Bhiwandi) via NH-48
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T10',
                'status' => TripStatus::Completed,
                'trip_type' => TripType::Domestic,
                'transport_mode' => TripTransportationMode::Road,
                'driver_name' => 'Harpreet Singh',
                'driver_phone' => '9810345678',
                'driver_license' => 'DL0120180067890',
                'vehicle_number' => 'DL01CZ8833',
                'vehicle_type' => 'truck',
                'is_verification_done' => true,
                'cargo_type' => 'Steel Coils',
                'cargo_description' => 'Hot rolled steel coils, 1-tonne coils individually wrapped',
                'hs_code' => '7208.27',
                'gross_weight' => 24000.00,
                'net_weight' => 24000.00,
                'weight_unit' => 'kg',
                'quantity' => 24,
                'quantity_unit' => 'coils',
                'declared_cargo_value' => 1800000.00,
                'invoice_number' => 'VL-DOM-2024-0345',
                'invoice_date' => now()->subDays(32)->toDateString(),
                'eway_bill_number' => '2312100200300400',
                'eway_bill_validity_date' => now()->subDays(18)->toDateString(),
                'dispatch_location_name' => 'Verma Logistics — Mayapuri HO',
                'dispatch_address' => 'Plot 14, Phase II, Mayapuri Industrial Area',
                'dispatch_city' => 'New Delhi',
                'dispatch_state' => 'Delhi',
                'dispatch_pincode' => '110064',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Kiran Verma',
                'dispatch_contact_number' => '9876543205',
                'dispatch_lat' => 28.6358,
                'dispatch_lng' => 77.1022,
                'dispatch_date' => now()->subDays(30)->toDateString(),
                'delivery_location_name' => 'Bhiwandi Logistics Hub',
                'delivery_address' => 'Plot 22, Bhiwandi Warehousing Complex, Mankoli',
                'delivery_city' => 'Mumbai',
                'delivery_state' => 'Maharashtra',
                'delivery_pincode' => '421302',
                'delivery_country' => 'India',
                'delivery_contact_person' => 'Receiving Manager',
                'delivery_contact_number' => '9820011223',
                'delivery_lat' => 19.2963,
                'delivery_lng' => 73.0517,
                'trip_start_time' => now()->subDays(30),
                'expected_delivery_date' => now()->subDays(28)->toDateString(),
                'actual_delivery_date' => now()->subDays(28)->toDateString(),
                'trip_end_time' => now()->subDays(28),
                'epod_status' => 'completed',
                'epod_confirmed_at' => now()->subDays(27),
                'epod_confirmation_notes' => 'All 24 coils received. 1 coil had minor surface rust but was accepted.',
                'last_known_lat' => 19.2963,
                'last_known_lng' => 73.0517,
                'last_known_source' => 'driver_mobile',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::Used,
            ],

            // ─────────────────────────────────────────────────────────────────
            // VL-T11 | DRAFT — Export not started
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_VL_T11',
                'status' => TripStatus::Draft,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Multimodal,
                'container_number' => 'CMAU9900001',
                'container_type' => '40HC',
                'carrier_scac' => 'CMDU',
                'cargo_type' => 'Finished Leather Goods',
                'cargo_description' => 'Leather bags, wallets and accessories in master cartons',
                'hs_code' => '4202.21',
                'gross_weight' => 4200.00,
                'net_weight' => 3900.00,
                'weight_unit' => 'kg',
                'quantity' => 850,
                'quantity_unit' => 'pieces',
                'declared_cargo_value' => 3400000.00,
                'invoice_number' => 'VL-EXP-2024-0620',
                'invoice_date' => now()->subDays(1)->toDateString(),
                'dispatch_location_name' => 'Verma Logistics — Mayapuri HO',
                'dispatch_city' => 'New Delhi',
                'dispatch_state' => 'Delhi',
                'dispatch_country' => 'India',
                'dispatch_lat' => 28.6358,
                'dispatch_lng' => 77.1022,
                'dispatch_date' => now()->addDays(5)->toDateString(),
                'delivery_location_name' => 'Jebel Ali Port',
                'delivery_city' => 'Dubai',
                'delivery_country' => 'UAE',
                'delivery_lat' => 24.9857,
                'delivery_lng' => 55.0272,
                'origin_port_name' => 'Jawaharlal Nehru Port (JNPT)',
                'origin_port_code' => 'INNSA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Jebel Ali Port',
                'destination_port_code' => 'AEJEA',
                'destination_port_category' => 'port',
                'expected_delivery_date' => now()->addDays(30)->toDateString(),
                'epod_status' => 'pending',
                'needs_seal' => false,
            ],
        ];
    }

    // ── IYER IMPEX (Chennai-based) ────────────────────────────────────────────

    private function iyerTrips(): array
    {
        return [

            // ─────────────────────────────────────────────────────────────────
            // II-T01 | COMPLETED EXPORT SEA
            // Chennai Port → (Colombo transshipment) → Hamburg
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T01',
                'status' => TripStatus::Completed,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Sea,
                'container_number' => 'MSCU3301245',
                'container_type' => '40HC',
                'carrier_scac' => 'MSCU',
                'cargo_type' => 'Automotive Parts',
                'cargo_description' => 'Two-wheeler gearboxes and clutch assemblies, export to Germany',
                'hs_code' => '8714.99',
                'gross_weight' => 16200.00,
                'net_weight' => 15800.00,
                'weight_unit' => 'kg',
                'quantity' => 540,
                'quantity_unit' => 'pieces',
                'declared_cargo_value' => 2800000.00,
                'invoice_number' => 'II-EXP-2024-0290',
                'invoice_date' => now()->subDays(62)->toDateString(),
                'dispatch_location_name' => 'Chennai Port (Kamarajar Port)',
                'dispatch_address' => 'Rajaji Salai, George Town',
                'dispatch_city' => 'Chennai',
                'dispatch_state' => 'Tamil Nadu',
                'dispatch_pincode' => '600001',
                'dispatch_country' => 'India',
                'dispatch_lat' => 13.0836,
                'dispatch_lng' => 80.2969,
                'dispatch_date' => now()->subDays(60)->toDateString(),
                'delivery_location_name' => 'Hamburger Hafen Terminal (HHLA)',
                'delivery_address' => 'Am Kaiserkai 45, 20457 Hamburg',
                'delivery_city' => 'Hamburg',
                'delivery_state' => 'Hamburg',
                'delivery_pincode' => '20457',
                'delivery_country' => 'Germany',
                'delivery_lat' => 53.5439,
                'delivery_lng' => 9.9569,
                'origin_port_name' => 'Chennai Port (Kamarajar Port)',
                'origin_port_code' => 'INMAA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Port of Hamburg',
                'destination_port_code' => 'DEHAM',
                'destination_port_category' => 'port',
                'vessel_name' => 'MSC OSCAR',
                'vessel_imo_number' => 'IMO9703291',
                'voyage_number' => 'AE3-789W',
                'bill_of_lading' => 'MSCCHN7890123',
                'eta' => now()->subDays(28),
                'etd' => now()->subDays(58),
                'trip_start_time' => now()->subDays(60),
                'expected_delivery_date' => now()->subDays(26)->toDateString(),
                'actual_delivery_date' => now()->subDays(26)->toDateString(),
                'trip_end_time' => now()->subDays(26),
                'epod_status' => 'completed',
                'epod_confirmed_at' => now()->subDays(25),
                'epod_confirmation_notes' => 'All 540 pieces received by Hamburg consignee. No damage.',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::Used,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T02 | ACTIVE — ON_VESSEL (Shanghai → Chennai)
            // Currently in Bay of Bengal, 3 days from Chennai
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T02',
                'status' => TripStatus::OnVessel,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Multimodal,
                'container_number' => 'CSCL9823011',
                'container_type' => '40GP',
                'carrier_scac' => 'CSCL',
                'cargo_type' => 'Solar Panels & Inverters',
                'cargo_description' => 'Monocrystalline solar panels (400W) and string inverters packed in OEM cartons',
                'hs_code' => '8541.40',
                'gross_weight' => 20500.00,
                'net_weight' => 19800.00,
                'weight_unit' => 'kg',
                'quantity' => 500,
                'quantity_unit' => 'panels',
                'declared_cargo_value' => 3600000.00,
                'invoice_number' => 'II-IMP-2024-0510',
                'invoice_date' => now()->subDays(22)->toDateString(),
                'dispatch_location_name' => 'Port of Shanghai (Yangshan)',
                'dispatch_address' => 'Yangshan Deep Water Port, Shengsi County',
                'dispatch_city' => 'Shanghai',
                'dispatch_country' => 'China',
                'dispatch_lat' => 30.6218,
                'dispatch_lng' => 122.0580,
                'dispatch_date' => now()->subDays(20)->toDateString(),
                'delivery_location_name' => 'Iyer Impex — Ambattur Factory',
                'delivery_address' => 'Survey No. 45, Ambattur Industrial Estate',
                'delivery_city' => 'Chennai',
                'delivery_state' => 'Tamil Nadu',
                'delivery_pincode' => '600058',
                'delivery_country' => 'India',
                'delivery_lat' => 13.1156,
                'delivery_lng' => 80.1551,
                'origin_port_name' => 'Port of Shanghai (Yangshan)',
                'origin_port_code' => 'CNSHA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Chennai Port (Kamarajar Port)',
                'destination_port_code' => 'INMAA',
                'destination_port_category' => 'port',
                'vessel_name' => 'CSCL GLOBE',
                'vessel_imo_number' => 'IMO9695154',
                'voyage_number' => 'AE9-021E',
                'bill_of_lading' => 'CSCLCHN9823011',
                'eta' => now()->addDays(3),
                'etd' => now()->subDays(18),
                'trip_start_time' => now()->subDays(20),
                'expected_delivery_date' => now()->addDays(8)->toDateString(),
                // Currently Bay of Bengal (12.5°N, 84.0°E)
                'last_known_lat' => 12.5000,
                'last_known_lng' => 84.0000,
                'last_known_source' => 'vessel_ais',
                'last_tracked_at' => now()->subHours(2),
                'last_vessel_tracked_at' => now()->subHours(2),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T03 | ACTIVE — IN_TRANSIT (road: Chennai Factory → Chennai Port)
            // Short road leg (~20km) heading to port for export stuffing
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T03',
                'status' => TripStatus::InTransit,
                'trip_type' => TripType::Export,
                'transport_mode' => TripTransportationMode::Multimodal,
                'driver_name' => 'Murugan Selvan',
                'driver_phone' => '9840123456',
                'driver_license' => 'TN0420190045678',
                'vehicle_number' => 'TN09CH3344',
                'vehicle_type' => 'container_carrier',
                'is_verification_done' => true,
                'container_number' => 'EGLV4501234',
                'container_type' => '20GP',
                'carrier_scac' => 'EGLV',
                'cargo_type' => 'Processed Food — Spices',
                'cargo_description' => 'Packaged cumin, coriander and pepper spices in sealed pouches, export to Germany',
                'hs_code' => '0909.21',
                'gross_weight' => 5800.00,
                'net_weight' => 5600.00,
                'weight_unit' => 'kg',
                'quantity' => 2800,
                'quantity_unit' => 'pouches',
                'declared_cargo_value' => 560000.00,
                'invoice_number' => 'II-EXP-2024-0598',
                'invoice_date' => now()->subDays(2)->toDateString(),
                'eway_bill_number' => '3313100200300400',
                'eway_bill_validity_date' => now()->addDays(12)->toDateString(),
                'dispatch_location_name' => 'Iyer Impex — Ambattur Factory',
                'dispatch_address' => 'Survey No. 45, Ambattur Industrial Estate',
                'dispatch_city' => 'Chennai',
                'dispatch_state' => 'Tamil Nadu',
                'dispatch_pincode' => '600058',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Meena Iyer',
                'dispatch_contact_number' => '9876543206',
                'dispatch_lat' => 13.1156,
                'dispatch_lng' => 80.1551,
                'dispatch_date' => now()->subDays(1)->toDateString(),
                'delivery_location_name' => 'Hamburger Hafen Terminal (HHLA)',
                'delivery_city' => 'Hamburg',
                'delivery_country' => 'Germany',
                'delivery_lat' => 53.5439,
                'delivery_lng' => 9.9569,
                'origin_port_name' => 'Chennai Port (Kamarajar Port)',
                'origin_port_code' => 'INMAA',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Port of Hamburg',
                'destination_port_code' => 'DEHAM',
                'destination_port_category' => 'port',
                'trip_start_time' => now()->subDays(1),
                'expected_delivery_date' => now()->addDays(35)->toDateString(),
                // Near Chennai port approach (Rajaji Salai)
                'last_known_lat' => 13.1100,
                'last_known_lng' => 80.2200,
                'last_known_source' => 'driver_mobile',
                'last_tracked_at' => now()->subMinutes(30),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T04 | COMPLETED DOMESTIC ROAD (Chennai → Bengaluru)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T04',
                'status' => TripStatus::Completed,
                'trip_type' => TripType::Domestic,
                'transport_mode' => TripTransportationMode::Road,
                'driver_name' => 'Balaji Krishnaswamy',
                'driver_phone' => '9944001122',
                'driver_license' => 'TN0120190034567',
                'vehicle_number' => 'TN01BZ6677',
                'vehicle_type' => 'truck',
                'is_verification_done' => true,
                'cargo_type' => 'IT Equipment',
                'cargo_description' => 'Servers, switches and network equipment for data centre',
                'hs_code' => '8471.49',
                'gross_weight' => 3200.00,
                'net_weight' => 3000.00,
                'weight_unit' => 'kg',
                'quantity' => 24,
                'quantity_unit' => 'racks',
                'declared_cargo_value' => 4500000.00,
                'invoice_number' => 'II-DOM-2024-0200',
                'invoice_date' => now()->subDays(18)->toDateString(),
                'eway_bill_number' => '3313200300400500',
                'eway_bill_validity_date' => now()->subDays(5)->toDateString(),
                'dispatch_location_name' => 'Iyer Impex — Ambattur Factory',
                'dispatch_address' => 'Survey No. 45, Ambattur Industrial Estate',
                'dispatch_city' => 'Chennai',
                'dispatch_state' => 'Tamil Nadu',
                'dispatch_pincode' => '600058',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Meena Iyer',
                'dispatch_contact_number' => '9876543206',
                'dispatch_lat' => 13.1156,
                'dispatch_lng' => 80.1551,
                'dispatch_date' => now()->subDays(16)->toDateString(),
                'delivery_location_name' => 'Iyer Impex — Bengaluru Warehouse',
                'delivery_address' => 'Shed 7, Electronic City Phase 2',
                'delivery_city' => 'Bengaluru',
                'delivery_state' => 'Karnataka',
                'delivery_pincode' => '560100',
                'delivery_country' => 'India',
                'delivery_contact_person' => 'Suresh Babu',
                'delivery_contact_number' => '9845011234',
                'delivery_lat' => 12.8441,
                'delivery_lng' => 77.6689,
                'trip_start_time' => now()->subDays(16),
                'expected_delivery_date' => now()->subDays(15)->toDateString(),
                'actual_delivery_date' => now()->subDays(15)->toDateString(),
                'trip_end_time' => now()->subDays(15),
                'epod_status' => 'completed',
                'epod_confirmed_at' => now()->subDays(14),
                'epod_confirmation_notes' => 'All 24 racks received. No physical damage.',
                'last_known_lat' => 12.8441,
                'last_known_lng' => 77.6689,
                'needs_seal' => true,
                'seal_final_status' => SealStatus::Used,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T05 | ACTIVE — AT_PORT (Singapore container at Chennai Port, customs)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T05',
                'status' => TripStatus::AtPort,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Sea,
                'container_number' => 'SGSIN5501234',
                'container_type' => '40HC',
                'carrier_scac' => 'OOLU',
                'cargo_type' => 'Polymer Granules',
                'cargo_description' => 'HDPE and PP polymer pellets in 25kg woven bags, 600 bags',
                'hs_code' => '3901.10',
                'gross_weight' => 15500.00,
                'net_weight' => 15000.00,
                'weight_unit' => 'kg',
                'quantity' => 600,
                'quantity_unit' => 'bags',
                'declared_cargo_value' => 900000.00,
                'invoice_number' => 'II-IMP-2024-0480',
                'invoice_date' => now()->subDays(12)->toDateString(),
                'dispatch_location_name' => 'Port of Singapore (PSA)',
                'dispatch_city' => 'Singapore',
                'dispatch_country' => 'Singapore',
                'dispatch_lat' => 1.2566,
                'dispatch_lng' => 103.8198,
                'dispatch_date' => now()->subDays(10)->toDateString(),
                'delivery_location_name' => 'Iyer Impex — Ambattur Factory',
                'delivery_city' => 'Chennai',
                'delivery_country' => 'India',
                'delivery_lat' => 13.1156,
                'delivery_lng' => 80.1551,
                'origin_port_name' => 'Port of Singapore (PSA)',
                'origin_port_code' => 'SGSIN',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Chennai Port (Kamarajar Port)',
                'destination_port_code' => 'INMAA',
                'destination_port_category' => 'port',
                'vessel_name' => 'OOCL HONG KONG',
                'vessel_imo_number' => 'IMO9776195',
                'voyage_number' => 'AE2-334E',
                'bill_of_lading' => 'OOLUSGP5501234',
                'eta' => now()->subDays(2),
                'etd' => now()->subDays(8),
                'trip_start_time' => now()->subDays(10),
                'expected_delivery_date' => now()->addDays(5)->toDateString(),
                'last_known_lat' => 13.0836,
                'last_known_lng' => 80.2969,
                'last_known_source' => 'vessel_ais',
                'last_tracked_at' => now()->subHours(12),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T06 | ACTIVE — VESSEL_ARRIVED (Singapore → Chennai, customs hold)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T06',
                'status' => TripStatus::VesselArrived,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Multimodal,
                'container_number' => 'APLU3301122',
                'container_type' => '20GP',
                'carrier_scac' => 'APLU',
                'cargo_type' => 'Speciality Chemicals',
                'cargo_description' => 'Epoxy resin and hardener system, non-hazardous grade',
                'hs_code' => '3907.30',
                'gross_weight' => 11000.00,
                'net_weight' => 10800.00,
                'weight_unit' => 'kg',
                'quantity' => 200,
                'quantity_unit' => 'drums',
                'declared_cargo_value' => 2200000.00,
                'invoice_number' => 'II-IMP-2024-0490',
                'invoice_date' => now()->subDays(16)->toDateString(),
                'dispatch_location_name' => 'Port of Singapore (PSA)',
                'dispatch_city' => 'Singapore',
                'dispatch_country' => 'Singapore',
                'dispatch_lat' => 1.2566,
                'dispatch_lng' => 103.8198,
                'dispatch_date' => now()->subDays(14)->toDateString(),
                'delivery_location_name' => 'Iyer Impex — Ambattur Factory',
                'delivery_city' => 'Chennai',
                'delivery_country' => 'India',
                'delivery_lat' => 13.1156,
                'delivery_lng' => 80.1551,
                'origin_port_name' => 'Port of Singapore (PSA)',
                'origin_port_code' => 'SGSIN',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Chennai Port (Kamarajar Port)',
                'destination_port_code' => 'INMAA',
                'destination_port_category' => 'port',
                'vessel_name' => 'APL SENTOSA',
                'vessel_imo_number' => 'IMO9632179',
                'voyage_number' => 'AE1-445E',
                'bill_of_lading' => 'APLUSGP3301122',
                'eta' => now()->subDays(1),
                'etd' => now()->subDays(12),
                'customs_hold' => true,
                'trip_start_time' => now()->subDays(14),
                'expected_delivery_date' => now()->addDays(6)->toDateString(),
                'last_known_lat' => 13.0836,
                'last_known_lng' => 80.2969,
                'last_known_source' => 'vessel_ais',
                'last_tracked_at' => now()->subHours(5),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T07 | DRAFT — Import, not started
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T07',
                'status' => TripStatus::Draft,
                'trip_type' => TripType::Import,
                'transport_mode' => TripTransportationMode::Sea,
                'container_number' => 'HLCU6601234',
                'container_type' => '40GP',
                'carrier_scac' => 'HLCU',
                'cargo_type' => 'Machine Tools',
                'cargo_description' => 'CNC lathe machines and milling attachments',
                'hs_code' => '8457.10',
                'gross_weight' => 28000.00,
                'net_weight' => 27500.00,
                'weight_unit' => 'kg',
                'quantity' => 8,
                'quantity_unit' => 'machines',
                'declared_cargo_value' => 8400000.00,
                'invoice_number' => 'II-IMP-2024-0530',
                'invoice_date' => now()->toDateString(),
                'dispatch_location_name' => 'Port of Hamburg',
                'dispatch_city' => 'Hamburg',
                'dispatch_country' => 'Germany',
                'dispatch_lat' => 53.5439,
                'dispatch_lng' => 9.9569,
                'dispatch_date' => now()->addDays(10)->toDateString(),
                'delivery_location_name' => 'Iyer Impex — Ambattur Factory',
                'delivery_city' => 'Chennai',
                'delivery_country' => 'India',
                'delivery_lat' => 13.1156,
                'delivery_lng' => 80.1551,
                'origin_port_name' => 'Port of Hamburg',
                'origin_port_code' => 'DEHAM',
                'origin_port_category' => 'port',
                'destination_port_name' => 'Chennai Port (Kamarajar Port)',
                'destination_port_code' => 'INMAA',
                'destination_port_category' => 'port',
                'expected_delivery_date' => now()->addDays(38)->toDateString(),
                'epod_status' => 'pending',
                'needs_seal' => false,
            ],

            // ─────────────────────────────────────────────────────────────────
            // II-T08 | ACTIVE — IN_TRANSIT DOMESTIC (Chennai → Delhi, NH-44)
            // ─────────────────────────────────────────────────────────────────
            [
                'trip_ref' => 'TR_II_T08',
                'status' => TripStatus::InTransit,
                'trip_type' => TripType::Domestic,
                'transport_mode' => TripTransportationMode::Road,
                'driver_name' => 'Ravi Shankar',
                'driver_phone' => '9900112233',
                'driver_license' => 'TN0120200056789',
                'vehicle_number' => 'TN22AJ7788',
                'vehicle_type' => 'truck',
                'is_verification_done' => true,
                'cargo_type' => 'Granite & Marble Slabs',
                'cargo_description' => 'Polished granite slabs, 2cm thick, secured in A-frames',
                'hs_code' => '2516.12',
                'gross_weight' => 20000.00,
                'net_weight' => 20000.00,
                'weight_unit' => 'kg',
                'quantity' => 200,
                'quantity_unit' => 'slabs',
                'declared_cargo_value' => 800000.00,
                'invoice_number' => 'II-DOM-2024-0280',
                'invoice_date' => now()->subDays(3)->toDateString(),
                'eway_bill_number' => '3313300400500600',
                'eway_bill_validity_date' => now()->addDays(8)->toDateString(),
                'dispatch_location_name' => 'Iyer Impex — Ambattur Factory',
                'dispatch_address' => 'Survey No. 45, Ambattur Industrial Estate',
                'dispatch_city' => 'Chennai',
                'dispatch_state' => 'Tamil Nadu',
                'dispatch_pincode' => '600058',
                'dispatch_country' => 'India',
                'dispatch_contact_person' => 'Meena Iyer',
                'dispatch_contact_number' => '9876543206',
                'dispatch_lat' => 13.1156,
                'dispatch_lng' => 80.1551,
                'dispatch_date' => now()->subDays(2)->toDateString(),
                'delivery_location_name' => 'ICD Tughlakabad',
                'delivery_address' => 'ICD Tughlakabad, Mathura Road',
                'delivery_city' => 'New Delhi',
                'delivery_state' => 'Delhi',
                'delivery_pincode' => '110044',
                'delivery_country' => 'India',
                'delivery_lat' => 28.5011,
                'delivery_lng' => 77.2877,
                'trip_start_time' => now()->subDays(2),
                'expected_delivery_date' => now()->addDays(2)->toDateString(),
                // Currently near Hyderabad on NH-44
                'last_known_lat' => 17.3850,
                'last_known_lng' => 78.4867,
                'last_known_source' => 'driver_mobile',
                'last_tracked_at' => now()->subHours(1),
                'epod_status' => 'pending',
                'needs_seal' => true,
                'seal_final_status' => SealStatus::InTransit,
            ],
        ];
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function seedEvents(Trip $trip, User $user): void
    {
        $statusFlow = [
            TripStatus::Draft,
            TripStatus::InTransit,
            TripStatus::AtPort,
            TripStatus::OnVessel,
            TripStatus::InTransshipment,
            TripStatus::VesselArrived,
            TripStatus::OutForDelivery,
            TripStatus::Delivered,
            TripStatus::Completed,
        ];

        $currentIndex = array_search($trip->status, $statusFlow);
        if ($currentIndex === false) $currentIndex = 0;

        $baseDaysAgo = match ($trip->status) {
            TripStatus::Completed => 45,
            TripStatus::Delivered => 16,
            TripStatus::OutForDelivery => 4,
            TripStatus::VesselArrived => 20,
            TripStatus::InTransshipment => 22,
            TripStatus::OnVessel => 15,
            TripStatus::AtPort => 8,
            TripStatus::InTransit => 3,
            default => 0,
        };

        for ($i = 0; $i <= $currentIndex; $i++) {
            $daysAgo = max(0, $baseDaysAgo - ($i * ($baseDaysAgo / max($currentIndex, 1))));
            TripEvent::insert([
                'customer_id' => $trip->customer_id,
                'trip_id' => $trip->id,
                'event_type' => $i === 0 ? 'trip_created' : 'status_changed',
                'previous_status' => $i > 0 ? $statusFlow[$i - 1]->value : null,
                'new_status' => $statusFlow[$i]->value,
                'event_data' => json_encode(['trip_ref' => $trip->trip_ref, 'triggered_by' => 'user']),
                'actor_type' => 'user',
                'actor_id' => $user->id,
                'created_at' => now()->subDays($daysAgo),
            ]);
        }

        if ($trip->vessel_name && $currentIndex >= 3) {
            TripEvent::insert([
                'customer_id' => $trip->customer_id,
                'trip_id' => $trip->id,
                'event_type' => 'vessel_info_added',
                'event_data' => json_encode([
                    'vessel_name' => $trip->vessel_name,
                    'imo' => $trip->vessel_imo_number,
                    'voyage_number' => $trip->voyage_number,
                    'bill_of_lading' => $trip->bill_of_lading,
                ]),
                'actor_type' => 'user',
                'actor_id' => $user->id,
                'created_at' => now()->subDays(max(0, $baseDaysAgo - 2)),
            ]);
        }
    }

    private function seedDocuments(Trip $trip, User $user): void
    {
        $docs = [
            ['doc_type' => 'e_way_bill', 'file_name' => 'EWayBill_' . $trip->trip_ref . '.pdf'],
            ['doc_type' => 'e_invoice', 'file_name' => 'EInvoice_' . $trip->trip_ref . '.pdf'],
        ];

        if (in_array($trip->status, [TripStatus::Delivered, TripStatus::Completed])) {
            $docs[] = ['doc_type' => 'e_pod', 'file_name' => 'ePOD_' . $trip->trip_ref . '.pdf'];
        }

        if ($trip->bill_of_lading) {
            $docs[] = ['doc_type' => 'supporting', 'file_name' => 'BL_' . $trip->bill_of_lading . '.pdf'];
        }

        foreach ($docs as $doc) {
            if (TripDocument::where('trip_id', $trip->id)->where('doc_type', $doc['doc_type'])->exists()) {
                continue;
            }
            TripDocument::insert([
                'trip_id' => $trip->id,
                'customer_id' => $trip->customer_id,
                'uploaded_by_id' => $user->id,
                'doc_type' => $doc['doc_type'],
                'file_name' => $doc['file_name'],
                'url' => "trips/{$trip->id}/documents/{$doc['file_name']}",
                'created_at' => now()->subDays(rand(1, 3)),
            ]);
        }
    }
}
